services:
  # base de donnée
  # Nom du service  
  mysql:  
    image: mysql:9
    container_name: rockny2_mysql
    ports:
      - 3306:3306
    volumes:
      - ./code/server/mysql:/app
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
  # serveur
  server:
    image: node:23
    container_name: rockny2_server
    ports:
      - 3000:3000
    volumes:
      - ./code/server:/app
    tty: true

  # client
  client:
    image: node:23
    container_name: rockny2_client
    ports:
      - 5173:5173
    volumes:
      - ./code/client:/app
    tty: true

  # mongo
  mongo:
    image: mongo:8
    ports:
      - 27017:27017
    volumes:
      - ./code/server/mongodb:/app
      - ./mongodb-data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
